/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iblogstreet_temcontrol_MainActivity */

#ifndef _Included_com_iblogstreet_temcontrol_MainActivity
#define _Included_com_iblogstreet_temcontrol_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iblogstreet_temcontrol_MainActivity
 * Method:    startTem
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iblogstreet_temcontrol_MainActivity_startTem
  (JNIEnv *, jobject);

/*
 * Class:     com_iblogstreet_temcontrol_MainActivity
 * Method:    stopTem
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iblogstreet_temcontrol_MainActivity_stopTem
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
