/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iblogstreet_alipay_pay_Payment */

#ifndef _Included_com_iblogstreet_alipay_pay_Payment
#define _Included_com_iblogstreet_alipay_pay_Payment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iblogstreet_alipay_MainActivity
 * Method:    pay
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_iblogstreet_alipay_MainActivity_pay
  (JNIEnv *, jobject, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
